### ISSUE TITLE
Refactor compile tasks

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-grsecurity#15]
The current state of `build-kernel-package` role in `develop` is leveraging static config files shipped with the role. Let's shoot for generating `.config` files instead, rather than reusing config files across different hosts.

As @ageis pointed out, we should improve how the filename for the built package is handled, because it'll include the kernel version, and therefore can't be hard-coded.

**Comment by ageis** [comment]
The output of `make-kpkg` is predictable, so if we just fill in part of `package_filename` with `linux_kernel_version` it should be good. From a quick glance at the manpage, it doesn't seem you can specify the output .deb filename (although you can append stuff to the version number).

As a side note, we are not intentionally not building the kernel headers here, because we don't anticipate needing them.

**Comment by conorsch** [comment]
I like that idea. You're right that the format is predictable, so we might as well set our expectations accordingly. It briefly occurred to me to use `with_fileglob` and `fetch`, but your way is safer and more predictable.

Also, we might want to differentiate the package names according to the value of `grsecurity_build_strategy`. Something like unaltered if `vanilla`, but add in `-for-ubuntu-`if `ubuntu`. I'd like some more concrete info on why we need the ubuntu overlay files at all—a quick test of installing the vanilla debs in an ubuntu 14.04 VM didn't show any problems, and `paxtest blackhat` results were good.

**Comment by conorsch** [comment]
Resolved by #20, among others.
