### ISSUE TITLE
sysctl flags

### ISSUE THREAD

**Issue by ageis** [freedomofpress/ansible-role-grsecurity#39]
The `install-grsec-kernel` role should eventually handle setting various sysctl parameters relevant to grsecurity, and then set the grsec_lock to 1.

**Comment by conorsch** [comment]
Enabling `grsec_lock` by default would likely cause more problems than it's worth, especially doing it by default. Setting it to true would forbid sysadmins from making any sysctl changes into the future, which is definitely not expected. If there are other sysctl settings that we should enforce, great, but I think most are already enabled by default given our `GRKERNSEC_SYSCTL_ON` setting in the kernel config. Still, doesn't hurt to be explicit.

Docs here for those interested: https://en.wikibooks.org/wiki/Grsecurity/Appendix/Sysctl_Options

**Comment by conorsch** [comment]
While I still feel that enabling grsec_lock by default is asking for trouble, I do agree that the install role can and should support setting grsecurity sysctl options. Perhaps an empty dict for sysctl values is the best approach, since it's extensible and would work well. 

Will take a look at sane default sysctl values for the dict and provide those; then folks with kernel options that affect availability of sysctl options can selectively override.

**Comment by conorsch** [comment]
Ported to https://github.com/freedomofpress/ansible-role-grsecurity-install/issues/1
