### ISSUE TITLE
gcc-4.9 not found by Debian or ubuntu/trusty64

### ISSUE THREAD

**Issue by ghost** [freedomofpress/ansible-role-grsecurity#46]
Hi,

My box sources for default debian and ubuntu builds does not find gcc-4.9 in either distro and I have to manually update the version numbers to 4.8 on each git pull. Could this be changed in the repo? It is unknown if this impacts nay other builds or not but I have not had a problem with this.

Thanks!

**Comment by conorsch** [comment]
@Andrew415 Are you using the base boxes provided in the repo's Vagrantfile? If not, please provide the base boxes you're using.

**Comment by ghost** [comment]
One is https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

I will need to look for which Debian image I was using a bit later.

**Comment by garrettr** [comment]
@Andrew415 Out of curiosity, which branch are you using: master or develop?

**Comment by ghost** [comment]
@garrettr master.

**Comment by garrettr** [comment]
@Andrew415 Ah, that's the cause of your issues. We've been doing development solely on the develop branch for a while now, so master is pretty out of date. We haven't merged it back into master because we've mostly been using this internally, so we haven't bothered having any kind of a coherent branching strategy or release schedule. Your issue was fixed on develop in ef36673cefce399b00b26129b46b12dca01605bb.

**Comment by ghost** [comment]
Ah ok that helps a lot, I'll try that branch on the other things I have been working on this weekend, cheers!

**Comment by conorsch** [comment]
> We've been doing development solely on the develop branch for a while now, so master is pretty out of date.

No longer true! The monstrous #35 brought master and develop to parity, and master is now the default branch for the repository. @Andrew415, you should be able to use the Vagrantfile on on master without any issues. If you find problems, holler!

**Comment by ageis** [comment]
Also, the build for Ubuntu trusty should use gcc-4.8...
