### ISSUE TITLE
Update version numbers throughout build.md

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-grsecurity#8]
The kernel version numbers currently listed in `build.md` are out of date. Worse, the URLs provided for the grsecurity patch and sig result in 404s:

```
$ wget https://grsecurity.net/stable/grsecurity-3.0-3.14.21-201410131959.patch{,.sig}
--2015-05-27 10:24:06--  https://grsecurity.net/stable/grsecurity-3.0-3.14.21-201410131959.patch
Resolving grsecurity.net (grsecurity.net)... 50.251.85.49
Connecting to grsecurity.net (grsecurity.net)|50.251.85.49|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-27 10:24:08 ERROR 404: Not Found.

--2015-05-27 10:24:08--  https://grsecurity.net/stable/grsecurity-3.0-3.14.21-201410131959.patch.sig
Reusing existing connection to grsecurity.net:443.
HTTP request sent, awaiting response... 404 Not Found
2015-05-27 10:24:08 ERROR 404: Not Found.
```

Maintaining this information by hand is a bit of a pain, but keeping the hard-coded values up-to-date within a six-month window seems reasonable. Additionally, the docs should link out to the [grsecurity download page](https://grsecurity.net/download.php) so folks know where to go if the hard-coded URLs don't work.

A new version of grsecurity was [released on 2015-05-22](https://grsecurity.net/stable/grsecurity-3.1-3.14.43-201505222221.patch). This version should be tested on VMs and hardware prior to updating the docs here.

**Comment by garrettr** [comment]
> Maintaining this information by hand is a bit of a pain, but keeping the hard-coded values up-to-date within a six-month window seems reasonable.

Since the grsecurity patches are updated _so_ frequently (at least weekly, on average), it is a pain to keep these numbers up to date. Additionally, spender only hosts the most recent version of the patches at any given time. That means that as soon as a new patch is put up, the links to the previous patch are 404 - so it is not possible to keep them up-to-date within a six month window.

I'd rather change the docs to clearly explain how to pick compatible Linux kernel versions with stable grsecurity patch versions, and then replace the specific version numbers in the document with placeholders so there can be no confusion.

**Comment by conorsch** [comment]
Superseded by #23 and #51.
