### ISSUE TITLE
Add reference to grsecurity store

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-grsecurity#9]
The documentation in this repository serves two main purposes:
1. publicize kernel build procedure for grsec kernel used in SecureDrop instances
2. provide instructions for folks who want to compile grsec kernel for non-SecureDrop projects

Folks who want to use grsecurity for non-SecureDrop projects may find the [grsecurity store](https://store.grsecurity.net/) useful. It's an officially maintained aspect of the grsecurity project that builds kernels on-demand.

**Comment by dolanjs** [comment]
@conorsch not that we link to it well in the README.md but we do have the process outlined for compiling the grsec kernel here: https://github.com/freedomofpress/grsec/blob/master/build.md

**Comment by conorsch** [comment]
@dolanjs Those docs are strong and should stay. For folks who don't want to run through the entire process by hand, the store may provide a middle-of-the-road approach of additional security with less effort. I think merely linking out to the store with a brief explanatory sentence would be sufficient.

**Comment by dolanjs** [comment]
@conorsch agreed. There are a few advantages to the grsec store rather than our build process.... 

### Pros
- Unique compiled kernels for each host which provides additional security advantages
- Kernels are updated for each release
- Directly supports the people who work and provide grsecurity

### Cons
- Since the kernels are not provided through a repo type solution it will require
  - manually retrieving each updated kernel per host via the authenticated url provided in email from the grsec store
  - transferring the downloaded kernels to the host
  - manually installing the kernel on the host.

**Comment by conorsch** [comment]
The grsecurity store is behind auth now, although it didn't use to be. Not sure if this is the same auth as a subscriber account, but I assume it is. Dig around for public URLs to place in the docs, or hit spender up for feedback on the best way to cite.

**Comment by conorsch** [comment]
The store is folded into subscriber benefits now, described here: https://grsecurity.net/business_support.php We should link out to that page for folks who want an automated build process as a service.
